layout_spectrum: 0.469534
color:
  saturation: 1
  brandStrength: 0.2608269
  lightness: 0.5681003
  rhythmicContrast: 1
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.08602151
name: I joined a gym
